### ISSUE TITLE
Merging cells to paste into Excel will appear misaligned

### ISSUE THREAD

**Issue by 174800** [dream-num/obsidian-univer#45]
### Describe the bug

![image](https://github.com/karlsbeard/obsidian-univer/assets/96051922/1170c61a-8e66-466b-86b5-19a4ea5d9d04)
Copying and pasting the data in the merged cells to Excel will cause misalignment.

### Steps to reproduce

Create a batch of data with merged cells in the univer-sheet and copy and paste it into Excel to reproduce it

### Expected behavior

I want to be able to paste it into Excel in the original format, some features are currently only available in Excel, such as creating charts

### Are you using the mobile app?

No

### Obsidian debug info

![image](https://github.com/karlsbeard/obsidian-univer/assets/96051922/aed985fb-1365-4c9e-a448-830c5c99d986)

**Comment by karlsbeard** [comment]
Thanks! Got it and will fix it as soon as possible.

**Comment by karlsbeard** [comment]
I have checked the bug and found it was caused by Univer self. I have proposed the issue to Univer. You can view it by the following link:
https://github.com/dream-num/univer/issues/1810
I will update the version when the Univer fixes this problem.

**Comment by jikkai** [comment]
Fixed

**Comment by 174800** [comment]
@jikkai 
Hello，jikkai，I updated univer and found that the problem still exists.
![image](https://github.com/dream-num/obsidian-univer/assets/96051922/7e0ddd7b-0845-49ce-9413-164bbe66577d)
![image](https://github.com/dream-num/obsidian-univer/assets/96051922/151c14a8-325b-45cc-bd81-36cc65c01fe0)

**Comment by jikkai** [comment]
> Hello，jikkai，I updated univer and found that the problem still exists.

We have already fixed this issue in Univer, but the Obsidian plugin hasn't been updated to the fixed version yet.
